#!/bin/sh -e

DIR=/var/www/ksc 
PRODUCTION_DIR=/var/www/html-ksc

echo "=== Starting post-receive... ==="

cd "$DIR"

status(){
    echo
    echo " ** $1"
    echo
}

run_git(){
    git --work-tree="$DIR" --git-dir="$DIR/.git" $@
}

rebuild(){

    status "merge and rebuild TEST site"

    run_git merge --ff master
    run_git checkout -f

    pushd "$DIR"
    ./site build || (./site clean && ./site build)
    chmod -R a+rw .
    popd

    status "TEST site updated: http://h209.it.helsinki.fi/test"
}

deploy(){
    status "Deploying..."

    rsync -av "$DIR/_site/" $PRODUCTION_DIR

    status "Site succesfully deployed!"
}

while read oldrev newrev refname
do
    branch=$(run_git rev-parse --symbolic --abbrev-ref $refname)

    status "Received branch $branch"

    if [ "master" == "$branch" ]; then
        rebuild

    elif ["production" == "$branch"]; then
        rebuild
        deploy
    else
        echo "Warning: unknown branch $branch, not building"
    fi
done
